/**
 * \file
 *
 * \brief AUTOSAR MemMap
 *
 * This file contains the implementation of the AUTOSAR
 * module MemMap.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*==================[inclusions]=============================================*/

#define MEMMAP_ERROR_CAN_17_MCMCAN

/*------------------[Start of a module]--------------------------------------*/

/* Memory section macros for Can_17_McmCan */

#if (defined CAN_17_MCMCAN_START_SEC_CODE)
  #undef CAN_17_MCMCAN_START_SEC_CODE
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CODE)
  #undef CAN_17_MCMCAN_STOP_SEC_CODE
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CODE_QM_GLOBAL)
  #undef CAN_17_MCMCAN_START_SEC_CODE_QM_GLOBAL
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CODE_QM_GLOBAL)
  #undef CAN_17_MCMCAN_STOP_SEC_CODE_QM_GLOBAL
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONFIG_DATA_QM_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONFIG_DATA_QM_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_CONST_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_CONST_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_CONST_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_CONST_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE0_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE1_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE2_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE3_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE4_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE4_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE5_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_CORE5_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#elif (defined CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_START_SEC_VAR_CLEARED_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
#elif (defined CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_GLOBAL_UNSPECIFIED)
  #undef CAN_17_MCMCAN_STOP_SEC_VAR_CLEARED_QM_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_CAN_17_MCMCAN

#endif

#if ((!defined MEMMAP_ERROR_CAN_17_MCMCAN) && (defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR
#elif ((defined MEMMAP_ERROR_CAN_17_MCMCAN) && (!defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR_CAN_17_MCMCAN
  #error MEMMAP_ERROR_CAN_17_MCMCAN the included memory section was not defined within the BSW-IMPLEMENTATION of Can_17_McmCan.
#endif
