/**
 * \file
 *
 * \brief AUTOSAR MemMap
 *
 * This file contains the implementation of the AUTOSAR
 * module MemMap.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2019 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*==================[inclusions]=============================================*/

#define MEMMAP_ERROR_ADC

/*------------------[Start of a module]--------------------------------------*/

/* Memory section macros for Adc */

#if (defined ADC_START_SEC_CODE_ASIL_B_GLOBAL)
  #undef ADC_START_SEC_CODE_ASIL_B_GLOBAL
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_CODE_ASIL_B_GLOBAL)
  #undef ADC_STOP_SEC_CODE_ASIL_B_GLOBAL
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_CONFIG_DATA_ASIL_B_GLOBAL_UNSPECIFIED)
  #undef ADC_START_SEC_CONFIG_DATA_ASIL_B_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_CONFIG_DATA_ASIL_B_GLOBAL_UNSPECIFIED)
  #undef ADC_STOP_SEC_CONFIG_DATA_ASIL_B_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_CONFIG_DATA_ASIL_B_CORE0_UNSPECIFIED)
  #undef ADC_START_SEC_CONFIG_DATA_ASIL_B_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_CONFIG_DATA_ASIL_B_CORE0_UNSPECIFIED)
  #undef ADC_STOP_SEC_CONFIG_DATA_ASIL_B_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_CONST_ASIL_B_GLOBAL_UNSPECIFIED)
  #undef ADC_START_SEC_CONST_ASIL_B_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_CONST_ASIL_B_GLOBAL_UNSPECIFIED)
  #undef ADC_STOP_SEC_CONST_ASIL_B_GLOBAL_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_CONST_ASIL_B_GLOBAL_8)
  #undef ADC_START_SEC_CONST_ASIL_B_GLOBAL_8
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_CONST_ASIL_B_GLOBAL_8)
  #undef ADC_STOP_SEC_CONST_ASIL_B_GLOBAL_8
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE0_UNSPECIFIED)
  #undef ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE0_UNSPECIFIED)
  #undef ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE0_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE1_UNSPECIFIED)
  #undef ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE1_UNSPECIFIED)
  #undef ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE1_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE2_UNSPECIFIED)
  #undef ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE2_UNSPECIFIED)
  #undef ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE2_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE3_UNSPECIFIED)
  #undef ADC_START_SEC_VAR_CLEARED_ASIL_B_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE3_UNSPECIFIED)
  #undef ADC_STOP_SEC_VAR_CLEARED_ASIL_B_CORE3_UNSPECIFIED
  #undef MEMMAP_ERROR_ADC

#elif (defined ADC_START_SEC_VAR_CLEARED_ASIL_B_GLOBAL_32)
  #undef ADC_START_SEC_VAR_CLEARED_ASIL_B_GLOBAL_32
  #undef MEMMAP_ERROR_ADC
#elif (defined ADC_STOP_SEC_VAR_CLEARED_ASIL_B_GLOBAL_32)
  #undef ADC_STOP_SEC_VAR_CLEARED_ASIL_B_GLOBAL_32
  #undef MEMMAP_ERROR_ADC
#endif

#if ((!defined MEMMAP_ERROR_ADC) && (defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR
#elif ((defined MEMMAP_ERROR_ADC) && (!defined MEMMAP_ERROR))
  #undef MEMMAP_ERROR_ADC
  #error MEMMAP_ERROR_ADC the included memory section was not defined within the BSW-IMPLEMENTATION of Adc.
#endif
