IF "%TARGET%"=="" SET TARGET=TRICORE
IF "%DERIVATE%"=="" SET DERIVATE=TC38XQ
IF "%TOOLCHAIN%"=="" SET TOOLCHAIN=tasking
SET TOOLPATH_COMPILER=%TASKING_TriCore_v6_3r1%
IF [%TRESOS_BASE%]==[] SET TRESOS_BASE=..\..\00_Tresos
IF [%PLUGINS_BASE%]==[] SET PLUGINS_BASE=%TRESOS_BASE%\plugins

SET WORK_BASE=D:\Projects\Projects\BL-3.9.2_ACG-8.7.1_TC38XQ
SET TEST_BASE=D:\Projects\Projects\BL-3.9.2_ACG-8.7.1_TC38XQ\test_base
SET MISRA_MODULE=Demo
SET MODULE_NAME=Demo
SET INTERNAL_MODULE_NAME=osc_Demo_OEMInd
SET MODULE_VARIANT=TS_TxDxM1I0R0
SET MODULE_ID=8.7.1-TC38XQ
SET Path=D:\Projects\EBA_Workspace\cygwin\bin;%Path%
SET AC_CYGWIN_DOS=D:\Projects\EBA_Workspace\cygwin