#ifndef SCHM_CAN_17_MCMCAN_H
#define SCHM_CAN_17_MCMCAN_H
/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file is the Module Interlink Header which contains the declarations relevant for that instance of a basic software module.
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.14
 * on Wed Mar 14 01:10:59 CET 2018. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* ==================[Includes]=============================================== */
#include <SchM_Can_17_McmCanType.h>

/* ==================[Declaration of functions with external linkage]========= */
/*#define RTE_START_SEC_CODE*/
#ifndef SCHM_CODE
#define SCHM_CODE
#endif
/*#include <MemMap.h>*/
extern void SchM_Enter_Can_17_McmCan_CanDisInt (void);
extern void SchM_Exit_Can_17_McmCan_CanDisInt (void);
extern void SchM_Enter_Can_17_McmCan_CanIntCtrl (void);
extern void SchM_Exit_Can_17_McmCan_CanIntCtrl (void);
extern void SchM_Enter_Can_17_McmCan_CanEnInt (void);
extern void SchM_Exit_Can_17_McmCan_CanEnInt (void);
extern void SchM_Enter_Can_17_McmCan_CanWrMO (void);
extern void SchM_Exit_Can_17_McmCan_CanWrMO (void);
/*#define RTE_STOP_SEC_CODE*/
/*#include <MemMap.h>*/

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif
/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
