
/*
 * To be used for mapping code to application block, boot block,
 * external flash etc
 */

#if 0 /* to be able to use #elif for every module */
#elif defined (FLSLOADER_START_SEC_CODE)
   #undef      FLSLOADER_START_SEC_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_CODE)
   #undef      FLSLOADER_STOP_SEC_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_START_SEC_WRITE_CODE)
  #if (PLATFORMS_TOOLCHAIN == PLATFORMS_tasking)
       #pragma section code "DRV_FLS_WRITE_SEC"
       #pragma section_name_with_symbol
       #pragma section_name_with_module
  #elif (PLATFORMS_TOOLCHAIN == PLATFORMS_dcc)
    #pragma section CODE ".DRV_FLS_WRITE_SEC"
  #endif

   #undef      FLSLOADER_START_SEC_WRITE_CODE
   #undef MEMMAP_ERROR
   
#elif defined (FLSLOADER_STOP_SEC_WRITE_CODE)
   #if (PLATFORMS_TOOLCHAIN == PLATFORMS_tasking)
        #pragma section code restore
   
  #elif (PLATFORMS_TOOLCHAIN == PLATFORMS_dcc)
    #pragma section CODE
  #endif

   #undef      FLSLOADER_STOP_SEC_WRITE_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_START_SEC_ERASE_CODE)
   #undef      FLSLOADER_START_SEC_ERASE_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_ERASE_CODE)
   #undef      FLSLOADER_STOP_SEC_ERASE_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_START_SEC_VAR_NOINIT_8BIT)
   #undef      FLSLOADER_START_SEC_VAR_NOINIT_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_NOINIT_8BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_NOINIT_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_START_SEC_VAR_NOINIT_16BIT)
   #undef      FLSLOADER_START_SEC_VAR_NOINIT_16BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_NOINIT_16BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_NOINIT_16BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_NOINIT_32BIT)
   #undef      FLSLOADER_START_SEC_VAR_NOINIT_32BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_NOINIT_32BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_NOINIT_32BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_NOINIT_UNSPECIFIED)
   #undef      FLSLOADER_START_SEC_VAR_NOINIT_UNSPECIFIED
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
   #undef      FLSLOADER_STOP_SEC_VAR_NOINIT_UNSPECIFIED
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_POWER_ON_INIT_8BIT)
   #undef      FLSLOADER_START_SEC_VAR_POWER_ON_INIT_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_8BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_8BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_POWER_ON_INIT_16BIT)
   #undef      FLSLOADER_START_SEC_VAR_POWER_ON_INIT_16BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_16BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_16BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_POWER_ON_INIT_32BIT)
   #undef      FLSLOADER_START_SEC_VAR_POWER_ON_INIT_32BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_32BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_32BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
   #undef      FLSLOADER_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
   #undef      FLSLOADER_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_FAST_8BIT)
   #undef      FLSLOADER_START_SEC_VAR_FAST_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_FAST_8BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_FAST_8BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_FAST_16BIT)
   #undef      FLSLOADER_START_SEC_VAR_FAST_16BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_FAST_16BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_FAST_16BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_FAST_32BIT)
   #undef      FLSLOADER_START_SEC_VAR_FAST_32BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_FAST_32BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_FAST_32BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_FAST_UNSPECIFIED)
   #undef      FLSLOADER_START_SEC_VAR_FAST_UNSPECIFIED
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_FAST_UNSPECIFIED)
   #undef      FLSLOADER_STOP_SEC_VAR_FAST_UNSPECIFIED
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_8BIT)
   #undef      FLSLOADER_START_SEC_VAR_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_8BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_8BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_16BIT)
   #undef      FLSLOADER_START_SEC_VAR_16BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_16BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_16BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_32BIT)
   #undef      FLSLOADER_START_SEC_VAR_32BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_32BIT)
   #undef      FLSLOADER_STOP_SEC_VAR_32BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_VAR_UNSPECIFIED)
   #undef      FLSLOADER_START_SEC_VAR_UNSPECIFIED
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_VAR_UNSPECIFIED)
   #undef      FLSLOADER_STOP_SEC_VAR_UNSPECIFIED
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_CONST_8BIT)
   #undef      FLSLOADER_START_SEC_CONST_8BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_CONST_8BIT)
   #undef      FLSLOADER_STOP_SEC_CONST_8BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_CONST_16BIT)
   #undef      FLSLOADER_START_SEC_CONST_16BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_CONST_16BIT)
   #undef      FLSLOADER_STOP_SEC_CONST_16BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_CONST_32BIT)
   #undef      FLSLOADER_START_SEC_CONST_32BIT
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_CONST_32BIT)
   #undef      FLSLOADER_STOP_SEC_CONST_32BIT
   #undef MEMMAP_ERROR


#elif defined (FLSLOADER_START_SEC_CONST_UNSPECIFIED)
   #undef      FLSLOADER_START_SEC_CONST_UNSPECIFIED
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_CONST_UNSPECIFIED)
   #undef      FLSLOADER_STOP_SEC_CONST_UNSPECIFIED
   #undef MEMMAP_ERROR

/*
Fls_Write API : Section
*/
#elif defined (FLSLOADER_START_SEC_WRITE_CODE)
   #undef      FLSLOADER_START_SEC_WRITE_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_WRITE_CODE)
   #undef      FLSLOADER_STOP_SEC_WRITE_CODE
   #undef MEMMAP_ERROR
/*
Fls Erase API : Section
*/
#elif defined (FLSLOADER_START_SEC_ERASE_CODE)
   #undef      FLSLOADER_START_SEC_ERASE_CODE
   #undef MEMMAP_ERROR
#elif defined (FLSLOADER_STOP_SEC_ERASE_CODE)
   #undef      FLSLOADER_STOP_SEC_ERASE_CODE
   #undef MEMMAP_ERROR

#endif

/* Deviation MISRA-1 <STOP> */

